package com.dndplatform.user.adapter.outbound.jpa.mapper;

import com.dndplatform.user.adapter.outbound.jpa.entity.UserEntity;
import com.dndplatform.user.domain.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

class UserEntityMapperTest {

    private UserEntityMapper sut;

    @BeforeEach
    void setUp() {
        sut = new UserEntityMapperImpl();
    }

    @Test
    void apply_shouldMapAllFieldsFromDomainToEntity() {
        LocalDateTime createdAt = LocalDateTime.of(2024, 3, 10, 8, 0);
        LocalDateTime updatedAt = LocalDateTime.of(2024, 9, 20, 16, 45);
        User user = new User(
                99L,
                "aragorn_king",
                "aragorn@gondor.com",
                "$2a$passwordhash",
                "DUNGEON_MASTER",
                true,
                createdAt,
                updatedAt
        );

        UserEntity result = sut.apply(user);

        assertThat(result).isNotNull();
        assertThat(result.getUsername()).isEqualTo("aragorn_king");
        assertThat(result.getEmail()).isEqualTo("aragorn@gondor.com");
        assertThat(result.getPasswordHash()).isEqualTo("$2a$passwordhash");
        assertThat(result.getRole()).isEqualTo("DUNGEON_MASTER");
        assertThat(result.getActive()).isTrue();
        assertThat(result.getCreatedAt()).isEqualTo(createdAt);
        assertThat(result.getUpdatedAt()).isEqualTo(updatedAt);
    }

    @Test
    void apply_shouldIgnoreId_whenMappingFromDomainToEntity() {
        User user = new User(
                999L,
                "legolas",
                "legolas@mirkwood.com",
                "hash",
                "PLAYER",
                true,
                LocalDateTime.now(),
                null
        );

        UserEntity result = sut.apply(user);

        // id must not be set — it is auto-generated by the DB
        assertThat(result).isNotNull();
        assertThat(result.id).isNull();
    }

    @Test
    void apply_shouldReturnNull_whenUserIsNull() {
        UserEntity result = sut.apply(null);

        assertThat(result).isNull();
    }

    @Test
    void apply_shouldHandleNullOptionalFields() {
        User user = new User(
                1L,
                "gimli",
                "gimli@erebor.com",
                "hash",
                "PLAYER",
                true,
                LocalDateTime.now(),
                null
        );

        UserEntity result = sut.apply(user);

        assertThat(result).isNotNull();
        assertThat(result.getUpdatedAt()).isNull();
    }
}
